sudo: false
language: python
cache:
  directories:
    - $HOME/.cache/pip

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev"

install:
  - pip install --upgrade pip wheel
  - pip --version
  - pip install .

script:
  - nosetests --with-doctest -P tests/ igdiscover/
