sudo: false
language: python
cache:
  directories:
    - $HOME/.cache/pip

python:
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels conda-forge --add channels defaults --add channels r --add channels bioconda
  - conda info -a
  - wget https://bitbucket.org/igdiscover/testdata/get/0.3.tar.gz
  - tar xvf 0.3.tar.gz

install:
  - conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION pip nose 'sqt>=0.8.0' seaborn 'snakemake!=3.13.2' cutadapt muscle pear flash 'igblast=1.5' 'vsearch=1.9.7' fastqc
  - source activate testenv
  - pip install .

script:
  - nosetests --with-doctest -P tests/ igdiscover/
  - igdiscover init --db igdiscover-testdata-*/db/ --reads igdiscover-testdata-*/reads.1.fastq.gz discovertest
  - cp igdiscover-testdata-*/igdiscover.yaml discovertest/
  - cd discovertest && igdiscover run
