sudo: false
language: python
cache:
  directories:
    - $HOME/.cache/pip

python:
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda config --add channels defaults --add channels conda-forge --add channels bioconda
  - conda info -a
  - wget https://bitbucket.org/igdiscover/testdata/get/v0.4.tar.gz
  - tar xvf v0.4.tar.gz

install:
  - conda env create -n testenv -f environment.yml
  - conda install -n testenv nose
  - source activate testenv
  - pip install .

script: tests/run.sh
