channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - nomkl
  - python=3.6
  - seaborn=0.9.*
  - sqt
  - snakemake-minimal
  - cutadapt>=2.3
  - muscle
  - pear
  - flash
  - igblast=1.10
  - ruamel.yaml
  - pigz>=2.4
  - dnaio
  - xopen>=0.7.3
  - pip
  - pip:
    - alignlib~=0.1.0
